POST http://localhost:8080/student
Content-Type: application/json

{
  "username" : "abdimilad",
  "password" : "123456",
  "firstName" :  "میلاد",
  "lastName" : "عبدی",
  "email" :  "miladabdi1374@gmail.com",
  "gender" : "male"
}

###
